#!/bin/bash

# ci_post_clone.sh
# This script runs automatically after Xcode Cloud clones the repository.
# It generates Secrets.xcconfig from environment variables set in App Store Connect.

set -e

echo "=== Xcode Cloud Post-Clone Script ==="
echo "Generating Secrets.xcconfig from environment variables..."

# Check if we're running in Xcode Cloud
if [ -z "$CI_PRIMARY_REPOSITORY_PATH" ]; then
    echo "Not running in Xcode Cloud. Skipping."
    exit 0
fi

# Check required environment variables
MISSING_VARS=""

if [ -z "$ALPACA_API_KEY" ]; then MISSING_VARS="$MISSING_VARS ALPACA_API_KEY"; fi
if [ -z "$ALPACA_API_SECRET" ]; then MISSING_VARS="$MISSING_VARS ALPACA_API_SECRET"; fi
if [ -z "$TWILIO_ACCOUNT_SID" ]; then MISSING_VARS="$MISSING_VARS TWILIO_ACCOUNT_SID"; fi
if [ -z "$TWILIO_AUTH_TOKEN" ]; then MISSING_VARS="$MISSING_VARS TWILIO_AUTH_TOKEN"; fi
if [ -z "$TWILIO_RECOVERY_CODE" ]; then MISSING_VARS="$MISSING_VARS TWILIO_RECOVERY_CODE"; fi
if [ -z "$TWILIO_VERIFY_SERVICE_SID" ]; then MISSING_VARS="$MISSING_VARS TWILIO_VERIFY_SERVICE_SID"; fi

if [ -n "$MISSING_VARS" ]; then
    echo "ERROR: Missing required environment variables:$MISSING_VARS"
    echo "Please add these in App Store Connect > Xcode Cloud > Workflow > Environment Variables"
    exit 1
fi

# Generate Secrets.xcconfig
cat > "$CI_PRIMARY_REPOSITORY_PATH/Secrets.xcconfig" << EOF
// Auto-generated by Xcode Cloud ci_post_clone.sh
// DO NOT EDIT - This file is generated at build time

// Alpaca API
ALPACA_API_KEY = $ALPACA_API_KEY
ALPACA_API_SECRET = $ALPACA_API_SECRET

// Twilio API
TWILIO_ACCOUNT_SID = $TWILIO_ACCOUNT_SID
TWILIO_AUTH_TOKEN = $TWILIO_AUTH_TOKEN
TWILIO_RECOVERY_CODE = $TWILIO_RECOVERY_CODE
TWILIO_VERIFY_SERVICE_SID = $TWILIO_VERIFY_SERVICE_SID
EOF

echo "Secrets.xcconfig generated successfully at: $CI_PRIMARY_REPOSITORY_PATH/Secrets.xcconfig"
echo "=== Post-Clone Script Complete ==="
